# Generated by Django 4.0.4 on 2022-05-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_user_alter_post_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
