# Generated by Django 4.0.4 on 2022-06-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_post_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
    ]
