# Generated by Django 4.0.4 on 2022-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_follow_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
