# Generated by Django 4.0.4 on 2022-06-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_follow_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testy',
        ),
        migrations.AddField(
            model_name='follow',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
            preserve_default=False,
        ),
    ]
