# Generated by Django 4.0.4 on 2022-06-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_delete_testy_follow_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='post',
        ),
        migrations.CreateModel(
            name='ManyPostManyFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.follow')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.post')),
            ],
        ),
    ]
